package com.hansel.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hansel.greendao.entity.User;
import com.hansel.greendao.entity.Address;

import com.hansel.greendao.UserDao;
import com.hansel.greendao.AddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig addressDaoConfig;

    private final UserDao userDao;
    private final AddressDao addressDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Address.class, addressDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        addressDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

}
